### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by ohthetrees** [ctberthiaume/gdcp#7] opened 2015-03-17 07:44 UTC
This is what I get after going through the credentials process. Not quite sure what is going on yet. This is on a OS X 10.10 machine with stock python build: `Python 2.7.6 (default, Sep  9 2014, 15:04:36)`

```
- Visit https://console.developers.google.com/
- Create a new project and select it
- Under 'APIs' make sure the 'Drive API' is turned on
- Under 'Credentials' create a new OAuth client ID
  Choose 'Installed -> Other' for application type
- Click 'Download JSON' to download the secrets file
- Copy the secrets file to /Users/cedar/.gdcp/client_secrets.json
sagan:~ cedar$ cp /Users/cedar/Downloads/client_secret_801904155613-1dqbs3tls262a173gapslqed3q5h75pk.apps.googleusercontent.com.json /Users/cedar/.gdcp/client_secrets.json
sagan:~ cedar$ gdcp -h
Traceback (most recent call last):
  File "/usr/local/bin/gdcp", line 1021, in <module>
    main()
  File "/usr/local/bin/gdcp", line 39, in main
    do_setup()
  File "/usr/local/bin/gdcp", line 127, in do_setup
    authorize()
  File "/usr/local/bin/gdcp", line 86, in authorize
    gauth.CommandLineAuth()
  File "/Library/Python/2.7/site-packages/pydrive/auth.py", line 69, in _decorated
    code = decoratee(self, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/pydrive/auth.py", line 198, in CommandLineAuth
    authorize_url = self.GetAuthUrl()
  File "/Library/Python/2.7/site-packages/pydrive/auth.py", line 385, in GetAuthUrl
    return self.flow.step1_get_authorize_url()
  File "/Library/Python/2.7/site-packages/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/oauth2client/client.py", line 1823, in step1_get_authorize_url
    return _update_query_params(self.auth_uri, query_params)
  File "/Library/Python/2.7/site-packages/oauth2client/client.py", line 431, in _update_query_params
    parts = urllib.parse.urlparse(uri)
AttributeError: 'Module_six_moves_urllib_parse' object has no attribute 'urlparse'
```

**Comment by ctberthiaume** [comment] 2015-04-07 21:58
Duplicate of #11

**Closed by ctberthiaume** 2015-04-07 21:58 UTC
Labels: bug, duplicate
